create table if not exists theme_update_suggestions (
  id bigint generated by default as identity primary key,
  theme_id bigint not null references themes(id) on delete cascade,
  source_name text not null,
  source_url text,
  suggested_changes jsonb not null,
  current_snapshot jsonb not null,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  reviewed_at timestamptz,
  reviewed_by text,
  created_at timestamptz not null default now()
);

alter table theme_update_suggestions enable row level security;

create policy "public read theme update suggestions" on theme_update_suggestions
for select using (false);

create index if not exists theme_update_suggestions_status_idx on theme_update_suggestions(status);
create index if not exists theme_update_suggestions_theme_id_idx on theme_update_suggestions(theme_id);
create index if not exists theme_update_suggestions_created_at_idx on theme_update_suggestions(created_at desc);
