-- Cafe/theme catalog for source-backed escape room data.
-- Keep subjective recommendation fields out of these tables first; add them after review.

create table if not exists cafes (
  id             bigint generated by default as identity primary key,
  normalized_key text not null unique,
  name           text not null,
  branch_name    text,
  area_label     text not null,
  district       text not null,
  address        text,
  phone          text,
  website_url    text,
  booking_url    text,
  source_url     text,
  status         text not null default 'active'
    check (status in ('active', 'closed', 'unknown', 'rejected')),
  needs_review   boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create table if not exists themes (
  id               bigint generated by default as identity primary key,
  cafe_id          bigint not null references cafes(id) on delete cascade,
  normalized_key   text not null,
  name             text not null,
  description      text,
  genre_labels     text[] not null default '{}',
  duration_minutes integer,
  min_players      integer,
  max_players      integer,
  price_text       text,
  price_per_person integer,
  image_url        text,
  booking_url      text,
  source_url       text,
  status           text not null default 'active'
    check (status in ('active', 'closed', 'unknown', 'rejected')),
  difficulty_label text,
  fear_label       text,
  needs_review     boolean not null default true,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint themes_cafe_normalized_key_unique unique (cafe_id, normalized_key)
);

create table if not exists theme_sources (
  id          uuid primary key default gen_random_uuid(),
  theme_id    bigint not null references themes(id) on delete cascade,
  source_name text not null,
  source_url  text not null,
  fetched_at  timestamptz not null default now(),
  raw_payload jsonb not null default '{}'::jsonb,
  constraint theme_sources_theme_source_url_unique unique (theme_id, source_url)
);

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists cafes_set_updated_at on cafes;
create trigger cafes_set_updated_at
before update on cafes
for each row execute function set_updated_at();

drop trigger if exists themes_set_updated_at on themes;
create trigger themes_set_updated_at
before update on themes
for each row execute function set_updated_at();

alter table cafes enable row level security;
alter table themes enable row level security;
alter table theme_sources enable row level security;

drop policy if exists "public read cafes" on cafes;
create policy "public read cafes" on cafes
for select using (status = 'active');

drop policy if exists "public read themes" on themes;
create policy "public read themes" on themes
for select using (status = 'active');

drop policy if exists "public read theme sources" on theme_sources;
create policy "public read theme sources" on theme_sources
for select using (true);

create index if not exists cafes_area_label_idx on cafes(area_label);
create index if not exists cafes_district_idx on cafes(district);
create index if not exists themes_cafe_id_idx on themes(cafe_id);
create index if not exists themes_status_idx on themes(status);
