-- Theme tags for editorial/community labels such as "100방", awards, and operation notes.
create table if not exists theme_tags (
  id          bigint generated by default as identity primary key,
  code        text not null unique,
  name        text not null,
  category    text not null default 'feature'
    check (category in ('award', 'community', 'feature', 'operation', 'audience', 'warning')),
  description text,
  sort_order  integer not null default 0,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists theme_taggings (
  id               bigint generated by default as identity primary key,
  theme_id         bigint not null references themes(id) on delete cascade,
  tag_id           bigint not null references theme_tags(id) on delete cascade,
  source_type      text not null default 'manual'
    check (source_type in ('manual', 'official', 'community', 'auto')),
  confidence_score integer
    check (confidence_score is null or (confidence_score >= 0 and confidence_score <= 100)),
  status           text not null default 'active'
    check (status in ('active', 'pending', 'hidden', 'rejected')),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint theme_taggings_theme_tag_unique unique (theme_id, tag_id)
);

create table if not exists theme_tag_sources (
  id          bigint generated by default as identity primary key,
  theme_id    bigint not null references themes(id) on delete cascade,
  tag_id      bigint not null references theme_tags(id) on delete cascade,
  source_name text not null,
  source_url  text,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

drop trigger if exists theme_tags_set_updated_at on theme_tags;
create trigger theme_tags_set_updated_at
before update on theme_tags
for each row execute function set_updated_at();

drop trigger if exists theme_taggings_set_updated_at on theme_taggings;
create trigger theme_taggings_set_updated_at
before update on theme_taggings
for each row execute function set_updated_at();

create index if not exists theme_tags_category_idx on theme_tags(category);
create index if not exists theme_tags_is_active_idx on theme_tags(is_active);
create index if not exists theme_taggings_tag_id_idx on theme_taggings(tag_id);
create index if not exists theme_taggings_status_idx on theme_taggings(status);
create index if not exists theme_tag_sources_theme_tag_idx on theme_tag_sources(theme_id, tag_id);

alter table theme_tags enable row level security;
alter table theme_taggings enable row level security;
alter table theme_tag_sources enable row level security;

drop policy if exists "public read active theme tags" on theme_tags;
create policy "public read active theme tags" on theme_tags
for select using (is_active = true);

drop policy if exists "public read active theme taggings" on theme_taggings;
create policy "public read active theme taggings" on theme_taggings
for select using (status = 'active');

drop policy if exists "public read theme tag sources" on theme_tag_sources;
create policy "public read theme tag sources" on theme_tag_sources
for select using (false);

insert into theme_tags (code, name, category, description, sort_order) values
  ('room_100', '100방', 'community', '100방 이상 플레이한 유저들에게 자주 언급되는 테마', 10),
  ('award_2024_grand_prize', '2024년 대상', 'award', '검수된 수상/랭킹 출처에서 2024년 대상급으로 확인된 테마', 20),
  ('award_2024_nominee', '2024년 후보', 'award', '검수된 수상/랭킹 출처에서 2024년 후보로 확인된 테마', 30),
  ('commercial', '영업용', 'operation', '대중 접객용으로 무난하다고 분류되는 테마', 40),
  ('beginner_friendly', '입문 추천', 'audience', '처음이거나 경험이 적은 사용자에게 추천하기 쉬운 테마', 50),
  ('strong_horror', '공포 강함', 'feature', '공포 강도가 높은 테마', 60),
  ('high_activity', '활동성 높음', 'feature', '움직임이나 활동성이 높은 테마', 70),
  ('actor', '배우 있음', 'feature', '배우/스태프 연출이 포함된 테마', 80),
  ('device_heavy', '장치 많음', 'feature', '장치 비중이 높은 테마', 90),
  ('emotional_pick', '감성 추천', 'audience', '감성/드라마 취향 사용자에게 추천하기 쉬운 테마', 100),
  ('outdoor', '야외', 'operation', '실외 이동 또는 야외 플레이가 포함된 테마', 110),
  ('online', '온라인', 'operation', '온라인으로 플레이하는 테마', 120),
  ('solo_available', '혼방 가능', 'operation', '1인 또는 혼자 예약/플레이가 가능한 테마', 130)
on conflict (code) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  sort_order = excluded.sort_order,
  is_active = true;
