-- Normalized filter metadata.
-- Regions intentionally use two levels only: region -> area (for example, 서울 -> 홍대).

create table if not exists regions (
  id         bigint generated by default as identity primary key,
  code       text not null unique,
  name       text not null,
  sort_order integer not null default 0
);

create table if not exists areas (
  id         bigint generated by default as identity primary key,
  region_id  bigint not null references regions(id) on delete cascade,
  code       text not null unique,
  name       text not null,
  sort_order integer not null default 0
);

create table if not exists genres (
  id         bigint generated by default as identity primary key,
  code       text not null unique,
  name       text not null,
  sort_order integer not null default 0
);

create table if not exists theme_genres (
  theme_id bigint not null references themes(id) on delete cascade,
  genre_id bigint not null references genres(id) on delete cascade,
  primary key (theme_id, genre_id)
);

alter table cafes
add column if not exists area_id bigint references areas(id);

insert into regions (code, name, sort_order) values
  ('seoul', '서울', 10),
  ('gyeonggi', '경기', 20),
  ('incheon', '인천', 30),
  ('busan', '부산', 40),
  ('daegu', '대구', 50),
  ('daejeon', '대전', 60),
  ('gwangju', '광주', 70),
  ('ulsan', '울산', 80),
  ('jeju', '제주', 90),
  ('other', '기타', 999)
on conflict (code) do update set
  name = excluded.name,
  sort_order = excluded.sort_order;

insert into areas (region_id, code, name, sort_order)
select r.id, a.code, a.name, a.sort_order
from regions r
join (
  values
    ('seoul', 'gangnam', '강남', 10),
    ('seoul', 'hongdae', '홍대', 20),
    ('seoul', 'geondae', '건대', 30),
    ('seoul', 'sinchon', '신촌', 40),
    ('seoul', 'seongsu', '성수', 50),
    ('seoul', 'jamsil', '잠실', 60),
    ('seoul', 'sillim', '신림', 70),
    ('seoul', 'nowon', '노원', 80),
    ('seoul', 'yongsan', '용산', 90),
    ('seoul', 'daehakro', '대학로', 100),
    ('gyeonggi', 'suwon', '수원', 10),
    ('incheon', 'bupyeong', '부평', 10),
    ('other', 'other', '기타', 999)
) as a(region_code, code, name, sort_order) on a.region_code = r.code
on conflict (code) do update set
  region_id = excluded.region_id,
  name = excluded.name,
  sort_order = excluded.sort_order;

insert into genres (code, name, sort_order) values
  ('Horror', '공포', 10),
  ('MysteryThriller', '미스터리/스릴러', 20),
  ('Emotional', '감성', 30),
  ('Comic', '코믹', 40),
  ('FantasyAdventure', '판타지/어드벤처', 50),
  ('Drama', '드라마', 60),
  ('Adventure', '어드벤처', 70),
  ('Crime', '범죄', 80),
  ('SF', 'SF', 90),
  ('Outdoor', '야외', 100),
  ('Online', '온라인', 110),
  ('Etc', '기타', 999)
on conflict (code) do update set
  name = excluded.name,
  sort_order = excluded.sort_order;

update cafes
set area_id = areas.id
from areas
where cafes.area_id is null
  and cafes.area_label = areas.name;

alter table regions enable row level security;
alter table areas enable row level security;
alter table genres enable row level security;
alter table theme_genres enable row level security;

drop policy if exists "public read regions" on regions;
create policy "public read regions" on regions
for select using (true);

drop policy if exists "public read areas" on areas;
create policy "public read areas" on areas
for select using (true);

drop policy if exists "public read genres" on genres;
create policy "public read genres" on genres
for select using (true);

drop policy if exists "public read theme genres" on theme_genres;
create policy "public read theme genres" on theme_genres
for select using (true);

create index if not exists cafes_area_id_idx on cafes(area_id);
create index if not exists areas_region_id_idx on areas(region_id);
create index if not exists theme_genres_genre_id_idx on theme_genres(genre_id);
