-- Curated external review links for each theme.
create table if not exists theme_review_links (
  id            bigint generated by default as identity primary key,
  theme_id      bigint not null references themes(id) on delete cascade,
  source_type   text not null check (source_type in ('blog', 'youtube', 'instagram', 'other')),
  title         text not null,
  url           text not null,
  author        text,
  published_at  date,
  thumbnail_url text,
  status        text not null default 'active' check (status in ('active', 'hidden')),
  sort_order    integer not null default 0,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint theme_review_links_url_unique unique (url)
);

create index if not exists theme_review_links_theme_id_idx on theme_review_links(theme_id);
create index if not exists theme_review_links_status_idx on theme_review_links(status);

drop trigger if exists theme_review_links_set_updated_at on theme_review_links;
create trigger theme_review_links_set_updated_at
before update on theme_review_links
for each row execute function set_updated_at();

alter table theme_review_links enable row level security;

drop policy if exists "public read active theme review links" on theme_review_links;
create policy "public read active theme review links" on theme_review_links
for select using (status = 'active');
