create table if not exists reports (
  id            bigint generated by default as identity primary key,
  report_token  uuid not null unique,
  theme_id      bigint references themes(id) on delete set null,
  report_type   text not null
    check (report_type in ('incorrect_info', 'closed_or_moved', 'missing_theme', 'bug', 'other')),
  title         text not null,
  message       text not null,
  reporter_name text,
  reporter_email text,
  page_url      text,
  user_agent    text,
  status        text not null default 'open'
    check (status in ('open', 'reviewing', 'resolved', 'rejected')),
  admin_note    text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

drop trigger if exists reports_set_updated_at on reports;
create trigger reports_set_updated_at
before update on reports
for each row execute function set_updated_at();

alter table reports enable row level security;

create policy "public insert reports" on reports
for insert with check (true);

create index if not exists reports_status_idx on reports(status);
create index if not exists reports_theme_id_idx on reports(theme_id);
create index if not exists reports_created_at_idx on reports(created_at desc);
